name: wellnor
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  equatable: ^1.0.0
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  http: ^0.12.1
  intl: ^0.16.1
  carousel_pro: ^1.0.0
  font_awesome_flutter: 8.8.1
  esc_pos_bluetooth: ^0.2.8
  shared_preferences: ^0.5.7+3
  charset_converter: ^1.0.3

  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img-placeholder.png
    - assets/images/empty_cart.png
    - assets/images/logo.jpg

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
